# Chạy test ở đây
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  # Không thay đổi ở đây tránh ảnh hưởng đến db nhé!
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT:8081}
