# Cấu hình spring jpa
spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # active application
  profiles:
    active: uat

  # cấu hình email
  mail:
    host: smtp.gmail.com
    port: 587
    #    username: vanhnekdungso74@gmail.com
    #    password: odbv zeup ignq lagi
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# value config dùng nhiều nơi
api:
  prefix:

# Jwt setup
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: ${JWT_SECRET}
  #  access-expiration-ms: 3600000        # 1 giờ
  #  refresh-expiration-ms: 2592000000    # 30 ngày
  accessExpiration: 604800 # 15 phút
  refreshExpiration: 604800 # 7 ngày

fe:
  #  url: ${FRONTEND_URL}
  url: http://localhost:5174/
